name: Build Android App

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  # Adjust Python version as needed

    - name: Install Buildozer and Dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libssl-dev \
            libffi-dev libsqlite3-dev libreadline-dev libbz2-dev liblzma-dev llvm libncursesw5-dev \
            xz-utils tk-dev libffi-dev liblzma-dev python-openssl git openjdk-8-jdk

    - name: Build Android Package
      run: |
        buildozer -v android debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-android
        path: project/.buildozer/apk/
